nome_completo=input('digite seu nome completo: ')
print(f'1-quantidade de caracteres: {len(nome_completo)}')
print(f'2-nome em maiusculo: {nome_completo.upper()}')
print(f'3-nome em minusculo: {nome_completo.lower()}')
print(f'4-nome sem espacos: {nome_completo.replace(' ', '')}')
print(f'5-tem somente letras?(e preciso tirar os espacos): {nome_completo.replace(' ','').isalpha()}')
print(f'6-e alfanumerico? tem letras ou numeros (e preciso tirar os espacos): {nome_completo.replace(' ','').isalnum()}')
print(f'7-cria um array com os itens: {nome_completo.split()}')
print(f'8-centralizar o nome em *')
print(nome_completo.center(80,'*'))